upsell:
  outputs:
    prod:
      schema: TM
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: "asia-southeast1"
      method: oauth
      project: vp-dwh-prod-c827
      threads: 10
      type: bigquery
      priority: batch
  target: prod
